[Путешествия]
ПЛАНЕТКА|https://www.youtube.com/feeds/videos.xml?channel_id=UCKaB4TBa1bsIotb-F7UYzrQ
Вован_карман|https://www.youtube.com/feeds/videos.xml?channel_id=UC4GvOTJ9d0YvI_W-GyDDypg

[Стендап-Комедия]
Stendup-№1|https://www.youtube.com/feeds/videos.xml?channel_id=UC3cJiUuZlpF-pkzqvSskTpg
SATYR|https://www.youtube.com/feeds/videos.xml?channel_id=UC4yxdlsaRT6WpZ_FZQ6uIpQ
Сева|https://www.youtube.com/feeds/videos.xml?channel_id=UCbSzLrXzlIvvuV7-DMzYt_A
Соболев|https://www.youtube.com/feeds/videos.xml?channel_id=UCuOyP59Q8OiqetsjABP8Hhw
Коваль|https://www.youtube.com/feeds/videos.xml?channel_id=UCp0QOno_8FOaGbn8gQujRHQ
HUGAEV|https://www.youtube.com/feeds/videos.xml?channel_id=UCZEXDMFttrcJo-ylzkcaE7g
ЭТО_ХОРОШО|https://www.youtube.com/feeds/videos.xml?channel_id=UCPT9_sNLoBLjH1uea7zpVIA

[Наука]
HOMO-DEUS|https://www.youtube.com/feeds/videos.xml?channel_id=UCDSU7aYPOHxstWvHurbH9VA
SciOne|https://www.youtube.com/feeds/videos.xml?channel_id=UCSaVoRErW4kqKsDqExs2MXA
Побединский-Физика|https://www.youtube.com/feeds/videos.xml?channel_id=UCQdPrDypfQeY5euAPbdc11g
Thosoi|https://www.youtube.com/feeds/videos.xml?channel_id=UCfTss6zXornNGh2RuXoh1EA
Watop|https://www.youtube.com/feeds/videos.xml?channel_id=UC8Q19ZrDKmxMiG3IABPggvQ
КикОбзор|https://www.youtube.com/feeds/videos.xml?channel_id=UCrzwOa2lzzPjfiLIn7Y8SrQ
Мальков-Эрголикбез|https://www.youtube.com/feeds/videos.xml?channel_id=UCPA91JeKp2rqg4bi2Q_OAxQ
Vert_Dider|https://www.youtube.com/feeds/videos.xml?channel_id=UCY6zVRa3Km52bsBmpyQnk6A


[Политика]
За_УГЛОМ|https://www.youtube.com/feeds/videos.xml?channel_id=UCUndA_nUiEeDVtEyxPhnkXw
ЮРА_СОВОК|https://www.youtube.com/feeds/videos.xml?channel_id=UCFg_qK2-Khw5voyJ0Eo2jtg

[DYI]
Огненое_ТВ|https://www.youtube.com/feeds/videos.xml?channel_id=UCONqLHFWVX6vbfJloiJptGg
Kasyan|https://www.youtube.com/feeds/videos.xml?channel_id=UCrNhJ4kI1GWRwZ0nmPJowTQ




